#!/bin/bash
#SBATCH --job-name=Lewislab_ATAC.%j.job
#SBATCH --partition=batch
#SBATCH --mail-type=ALL
#SBATCH --mail-user=seg75580@uga.edu
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=24
#SBATCH --mem=50gb
#SBATCH --time=48:00:00
#SBATCH --output=bwtMapATAC.%j.out
#SBATCH --error=ATAC.%j.err

cd $SLURM_SUBMIT_DIR

#read in variables from the config file ($threads, $FASTQ, $OUTDIR, )

source config_bwt.txt

OUTDIR=/scratch/seg75580/Run147/bowtieSbatch/${OutputFolderName}
mkdir ${OUTDIR}


# #process reads using trimGalore
#
ml Trim_Galore/0.6.10-GCCcore-12.3.0
trim_galore --paired --length 20 --fastqc --gzip -o ${OUTDIR}/TrimmedReads ${FASTQ}/*fastq\.gz
#
FILES="${OUTDIR}/TrimmedReads/*R1_001_val_1\.fq\.gz" #Don't forget the *
#
 mkdir "${OUTDIR}/SortedBamFiles"
 mkdir "${OUTDIR}/BigWigs"
 mkdir "${OUTDIR}/Peaks"
 mkdir "${OUTDIR}/Beds"
 mkdir "${OUTDIR}/Peaks/BroadPeaks"
#mkdir "$OUTDIR/HomerTagDirectories"
#mkdir "$OUTDIR/TdfFiles"
#
#Iterate over the files
for f in $FILES
do
#
# 	#Examples to Get Different parts of the file name
# 		#See here for details: http://tldp.org/LDP/abs/html/refcards.html#AEN22664
		#${string//substring/replacement}
# 		#dir=${f%/*}
		
	file=${f##*/}
	#remove ending from file name to create shorter names for bam files and other downstream output
	name=${file/%_S[1-12]*_L001_R1_001_val_1.fq.gz/}

#
# 	# File Vars
# 	#use sed to get the name of the second read matching the input file
	read2=$(echo "$f" | sed 's/R1_001_val_1\.fq\.gz/R2_001_val_2\.fq\.gz/g')
	#variable for naming bam file
 	bam="${OUTDIR}/SortedBamFiles/${name}.bam"
	shifted="${OUTDIR}/SortedBamFiles/${name}.shifted.bam"
  	deduped="${OUTDIR}/SortedBamFiles/${name}_deduped.bam"
  	bed="${OUTDIR}/Beds/${name}.bed"
	#variable name for bigwig output
	bigwig="${OUTDIR}/BigWigs/${name}"
	#QualityBam="${OUTDIR}/SortedBamFiles/${name}_Q30.bam"
#

ml SAMtools/1.16.1-GCC-11.3.0 
ml BWA/0.7.17-GCCcore-11.3.0
#
bwa mem -M -v 3 -a -t $THREADS $GENOME $f $read2 | samtools view -bhSu - | samtools sort -@ $THREADS -T $OUTDIR/SortedBamFiles/tempReps -o "$bam" -
samtools index "$bam"

############Abby's script#######################
module load picard/2.18.4-Java-1.8.0_241
#java -jar picard.jar MarkDuplicates \
java -jar $EBROOTPICARD/picard.jar MarkDuplicates \
    I=${bam} \
    O=${deduped} \
    M=${OUTDIR}/SortedBamFiles/${name}_marked_dup_metrics.txt \
    REMOVE_DUPLICATES=TRUE
samtools index "$deduped"


java -jar $EBROOTPICARD/picard.jar CollectInsertSizeMetrics \
    I=${deduped} \
    O=${OUTDIR}/SortedBamFiles/${name}_collect_insert_size_metrics.txt \
    H=${OUTDIR}/SortedBamFiles/${name}_insert_size_histogram.pdf \
    M=0.5 \
    VALIDATION_STRINGENCY=LENIENT QUIET=TRUE VERBOSITY=ERROR

module load deepTools/3.5.5-gfbf-2023a
alignmentSieve -p $THREADS --ATACshift --bam $deduped -o ${OUTDIR}/ShiftedBamFiles/${name}.tmp.bam

samtools sort -@ $THREADS -O bam -o ${shifted} ${OUTDIR}/ShiftedBamFiles/${name}.tmp.bam
samtools index -@ $THREADS ${shifted}
#############################################################


#module load picard/2.27.4-Java-13.0.2

#java -jar picard.jar MarkDuplicates \
 #     I=${bam} \
  #    O=${deduped} \
   #   M=./${OUTDIR}/SortedBamFiles/marked_dup_metrics.txt \
    #  --REMOVE_DUPLICATES=TRUE
    
#perl ./shiftTn5_BAM_2_BED.pl "${bam}" > "${name}.bed"

############################
# #deeptools
#module load deepTools/3.5.5-gfbf-2023a
#alignmentSieve -p $THREADS --ATACshift --bam ${bam} -o ${name}.tmp.bam

# the bam file needs to be sorted again
#samtools sort -@ $THREADS -O bam -o ${shifted} ${name}.tmp.bam
#samtools index -@ $THREADS ${shifted}
#rm ${name}.tmp.bam

#Plot all reads
bamCoverage -p $THREADS --Offset 1 1 -bs 1 --normalizeUsing BPM  -of bigwig -b ${shifted} -o "${bigwig}.ATAC_bin_1.Bulk.bw"
bamCoverage -p $THREADS --Offset 1 25 -bs 25 --normalizeUsing BPM --smoothLength 75 -of bigwig -b ${shifted} -o "${bigwig}.ATAC_bin_25_smooth_75.bw"


bamCoverage -p $THREADS --Offset 1 1 -bs 1 --normalizeUsing BPM  -of bigwig -b ${deduped} -o "${bigwig}.ATAC_bin_1.Bulk.bw"
bamCoverage -p $THREADS --Offset 1 25 -bs 25 --normalizeUsing BPM --smoothLength 75 -of bigwig -b ${deduped} -o "${bigwig}.ATAC_bin_25_smooth_75.bw"

module load module load MACS3/3.0.1-gfbf-2023a
##doing all samples at once
macs3 callpeak -t $deduped -c ${OUTDIR}/SortedBamFiles/${name}_deduped.bam --format BAMPE --outdir ${OUTDIR}/Peaks -n $name

#How Abby calls peaks
macs3 callpeak -t $shifted -c ${OUTDIR}/SortedBamFiles/152-N8_Genomic_SPF94_TR34_cyp51A_hph__Rep_1_S104_L006_R1_001_val_1.fq.gz.shifted.bam --format BAMPE --outdir ${OUTDIR}/Peaks/BroadPeaks -n ${name}_bampe --broad-cutoff 0.05 --broad --keep-dup all -q 0.01 -g 317634770

#macs3 callpeak -t $shifted -c ${OUTDIR}/SortedBamFiles/148-N6_ATAC_CEA17_gDNA__Rep1_S102_L003_R1_001_val_1.fq.gz.shifted.bam --format BAMPE --outdir ${OUTDIR}/reg_Peaks -n $name

#macs3 callpeak -t "${OUTDIR}/SortedBamFiles/147-N16_Genomic_P5_SPF235a_TR46_cyp51A_hph__Rep_1_Af_.bam" --outdir "${OUTDIR}/Peaks" -f BAMPE -g 41037538 -q 0.01 --nomodel --shift -100 --extsize 200 --keep-dup all –nolambda
#macs3 hmmratac -b $shifted --outdir ${OUTDIR}/hmmr_Peaks -n $name


#when doing one sample at a time
#macs3 callpeak -c ${OUTDIR}/SortedBamFiles/148-N6_ATAC_CEA17_gDNA__Rep1_S102_L003_R1_001_val_1.fq.gz.shifted.bam --format BAMPE --outdir ${OUTDIR}/reg_Peaks -n $name
done
